In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
df = pd.read_csv('weatherAUS.csv')
df.sample(5)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
83522,2016-02-27,Dartmoor,15.3,23.7,0.2,3.6,8.2,SW,31.0,NaN,...,92.0,56.0,1022.5,1021.0,NaN,NaN,16.1,22.0,No,No
13272,2012-05-20,Moree,3.5,22.9,0.0,3.0,10.3,ENE,26.0,E,...,36.0,16.0,1024.2,1020.3,1.0,1.0,14.4,22.3,No,No
71482,2012-01-25,Mildura,17.4,38.4,0.0,10.4,12.9,SE,48.0,SE,...,38.0,13.0,1012.5,1008.5,2.0,7.0,26.1,37.4,No,No
16622,2013-05-24,Newcastle,11.2,19.9,14.4,NaN,NaN,NaN,NaN,SE,...,61.0,50.0,NaN,NaN,6.0,5.0,18.6,19.0,Yes,Yes
16818,2013-12-06,Newcastle,11.5,22.0,0.0,NaN,NaN,NaN,NaN,SW,...,43.0,38.0,NaN,NaN,0.0,4.0,18.0,21.0,No,No

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           145460 non-null  object
 1   Location       145460 non-null  object
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  object
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  object
 10  WindDir3pm     141232 non-null  object
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null   float64
 18  Cloud3pm       86102 non-null   float64
 19  Temp9am        143693 non-null  float64
 20  Temp3pm        141851 non-null  float64
 21  RainToday      142199 non-null  object
 22  RainTomorrow   142193 non-null  object
dtypes: float64(16), object(7)
memory usage: 25.5+ MB

In [4]:
df.Date = pd.to_datetime(df.Date, format="%Y/%m/%d", errors='raise')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           145460 non-null  datetime64[ns]
 1   Location       145460 non-null  object
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  object
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  object
 10  WindDir3pm     141232 non-null  object
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null   float64
 18  Cloud3pm       86102 non-null   float64
 19  Temp9am        143693 non-null  float64
 20  Temp3pm        141851 non-null  float64
 21  RainToday      142199 non-null  object
 22  RainTomorrow   142193 non-null  object
dtypes: datetime64[ns](1), float64(16), object(6)
memory usage: 25.5+ MB

In [6]:
df["Year"]=pd.DatetimeIndex(df.Date).year
df["Month"]=pd.DatetimeIndex(df.Date).month
df["Day"]=pd.DatetimeIndex(df.Date).day

In [7]:
df.drop('Date', axis='columns', inplace= True)
df.sample(5)

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow,Year,Month,Day
40967,Williamtown,18.5,25.6,1.4,4.0,3.7,S,35.0,S,S,...,1014.0,7.0,5.0,22.2,25.0,Yes,No,2013,1,30
26017,Penrith,10.3,17.3,2.4,NaN,NaN,NW,39.0,NaN,WNW,...,NaN,NaN,NaN,11.4,13.6,Yes,No,2014,5,3
134958,Launceston,-1.1,14.3,0.0,NaN,NaN,ENE,7.0,NaN,NE,...,NaN,NaN,NaN,1.2,13.4,No,No,2014,6,9
46262,Canberra,-4.5,16.1,0.0,4.4,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.1,15.3,No,Yes,2009,9,6
76826,Portland,8.4,18.0,0.6,2.6,5.0,WNW,46.0,NNW,WNW,...,1015.2,NaN,NaN,13.4,17.7,No,Yes,2014,4,20

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 25 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Location       145460 non-null  object
 1   MinTemp        143975 non-null  float64
 2   MaxTemp        144199 non-null  float64
 3   Rainfall       142199 non-null  float64
 4   Evaporation    82670 non-null   float64
 5   Sunshine       75625 non-null   float64
 6   WindGustDir    135134 non-null  object
 7   WindGustSpeed  135197 non-null  float64
 8   WindDir9am     134894 non-null  object
 9   WindDir3pm     141232 non-null  object
 10  WindSpeed9am   143693 non-null  float64
 11  WindSpeed3pm   142398 non-null  float64
 12  Humidity9am    142806 non-null  float64
 13  Humidity3pm    140953 non-null  float64
 14  Pressure9am    130395 non-null  float64
 15  Pressure3pm    130432 non-null  float64
 16  Cloud9am       89572 non-null   float64
 17  Cloud3pm       86102 non-null   float64
 18  Temp9am        143693 non-null  float64
 19  Temp3pm        141851 non-null  float64
 20  RainToday      142199 non-null  object
 21  RainTomorrow   142193 non-null  object
 22  Year           145460 non-null  int64
 23  Month          145460 non-null  int64
 24  Day            145460 non-null  int64
dtypes: float64(16), int64(3), object(6)
memory usage: 27.7+ MB

In [9]:
np.mean(df.MinTemp)

12.19403438096892

In [10]:
def fill_missing_num_values(df):
    for col in df.columns:
        if df[col].dtypes in ["float64", "int64"]:
            df[col].fillna(np.mean(df[col]), inplace=True)

fill_missing_num_values(df)
df.sample(5)

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow,Year,Month,Day
140874,Darwin,17.6,31.0,0.0,7.400000,10.400000,NW,31.0,ESE,NW,...,1011.800000,4.000000,1.00000,23.3,28.7,No,No,2013,7,27
125450,SalmonGums,5.8,22.2,0.0,5.468232,7.611178,W,28.0,W,WSW,...,1015.255889,4.447461,4.50993,14.6,22.0,No,No,2013,9,13
22649,NorfolkIsland,14.6,18.3,0.0,2.800000,1.600000,SW,22.0,S,S,...,1021.900000,7.000000,7.00000,16.9,17.2,No,No,2013,6,8
101877,MountGambier,8.3,20.8,0.2,3.200000,9.000000,N,69.0,NNE,NNE,...,1012.700000,1.000000,3.00000,11.7,20.5,No,Yes,2015,8,20
77953,Portland,10.7,20.3,0.0,5.468232,7.611178,NNW,35.0,N,NNW,...,1016.500000,8.000000,1.00000,13.4,20.1,No,No,2017,5,21

In [11]:
df.dropna(axis=0, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 123710 entries, 0 to 145458
Data columns (total 25 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Location       123710 non-null  object
 1   MinTemp        123710 non-null  float64
 2   MaxTemp        123710 non-null  float64
 3   Rainfall       123710 non-null  float64
 4   Evaporation    123710 non-null  float64
 5   Sunshine       123710 non-null  float64
 6   WindGustDir    123710 non-null  object
 7   WindGustSpeed  123710 non-null  float64
 8   WindDir9am     123710 non-null  object
 9   WindDir3pm     123710 non-null  object
 10  WindSpeed9am   123710 non-null  float64
 11  WindSpeed3pm   123710 non-null  float64
 12  Humidity9am    123710 non-null  float64
 13  Humidity3pm    123710 non-null  float64
 14  Pressure9am    123710 non-null  float64
 15  Pressure3pm    123710 non-null  float64
 16  Cloud9am       123710 non-null  float64
 17  Cloud3pm       123710 non-null  float64
 18  Temp9am        123710 non-null  float64
 19  Temp3pm        123710 non-null  float64
 20  RainToday      123710 non-null  object
 21  RainTomorrow   123710 non-null  object
 22  Year           123710 non-null  int64
 23  Month          123710 non-null  int64
 24  Day            123710 non-null  int64
dtypes: float64(16), int64(3), object(6)
memory usage: 24.5+ MB

In [12]:
cat_columns = df.columns[df.dtypes=='object'].tolist()
cat_columns.remove("RainTomorrow")
num_columns = df.columns[df.dtypes=='float64'].tolist()

In [13]:
cat_columns

['Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm', 'RainToday']

In [14]:
# checking the values and counts in the object columns
def unique_values_in_object(df, columns):
    for col in columns:
        print(col, df[col].unique())
        print("-x-x-x--x-x-x--x--x-x--x")

unique_values_in_object(df, cat_columns)

Location ['Albury' 'BadgerysCreek' 'Cobar' 'CoffsHarbour' 'Moree' 'NorahHead'
 'NorfolkIsland' 'Penrith' 'Richmond' 'Sydney' 'SydneyAirport'
 'WaggaWagga' 'Williamtown' 'Wollongong' 'Canberra' 'Tuggeranong'
 'MountGinini' 'Ballarat' 'Bendigo' 'Sale' 'MelbourneAirport' 'Melbourne'
 'Mildura' 'Nhil' 'Portland' 'Watsonia' 'Dartmoor' 'Brisbane' 'Cairns'
 'GoldCoast' 'Townsville' 'Adelaide' 'MountGambier' 'Nuriootpa' 'Woomera'
 'Witchcliffe' 'PearceRAAF' 'PerthAirport' 'Perth' 'SalmonGums' 'Walpole'
 'Hobart' 'Launceston' 'AliceSprings' 'Darwin' 'Katherine' 'Uluru']
-x-x-x--x-x-x--x--x-x--x
WindGustDir ['W' 'WNW' 'WSW' 'NE' 'NNW' 'N' 'NNE' 'SW' 'ENE' 'SSE' 'S' 'NW' 'SE' 'ESE'
 'E' 'SSW']
-x-x-x--x-x-x--x--x-x--x
WindDir9am ['W' 'NNW' 'SE' 'ENE' 'SW' 'SSE' 'S' 'NE' 'SSW' 'N' 'WSW' 'ESE' 'E' 'NW'
 'WNW' 'NNE']
-x-x-x--x-x-x--x--x-x--x
WindDir3pm ['WNW' 'WSW' 'E' 'NW' 'W' 'SSE' 'ESE' 'ENE' 'NNW' 'SSW' 'SW' 'SE' 'N' 'S'
 'NNE' 'NE']
-x-x-x--x-x-x--x--x-x--x
RainToday ['No' 'Yes']
-x-x-x--x-x-x--x--x-x--x

In [15]:
def removing_categorical_column_as_per_variance(df, columns):
    dropped_columns = []
    for col in columns:
        if len(df[col].unique())>1:
            unique_obj_per = np.array(df[col].value_counts(normalize = True)* 100)
            var = np.var(unique_obj_per)
            if var<1:
                dropped_columns.append(col)
        else:
            dropped_columns.append(col)
    df.drop(dropped_columns, axis='columns', inplace=True)
#removing_categorical_column_as_per_variance(df, cat_columns)
df.head(5)

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow,Year,Month,Day
0,Albury,13.4,22.9,0.6,5.468232,7.611178,W,44.0,W,WNW,...,1007.1,8.000000,4.50993,16.9,21.8,No,No,2008,12,1
1,Albury,7.4,25.1,0.0,5.468232,7.611178,WNW,44.0,NNW,WSW,...,1007.8,4.447461,4.50993,17.2,24.3,No,No,2008,12,2
2,Albury,12.9,25.7,0.0,5.468232,7.611178,WSW,46.0,W,WSW,...,1008.7,4.447461,2.00000,21.0,23.2,No,No,2008,12,3
3,Albury,9.2,28.0,0.0,5.468232,7.611178,NE,24.0,SE,E,...,1012.8,4.447461,4.50993,18.1,26.5,No,No,2008,12,4
4,Albury,17.5,32.3,1.0,5.468232,7.611178,W,41.0,ENE,NW,...,1006.0,7.000000,8.00000,17.8,29.7,No,No,2008,12,5

In [16]:
df['RainTomorrow'].value_counts()["Yes"]/len(df['RainTomorrow'])*100

22.14210653948751

In [17]:
cat_columns = df.columns[df.dtypes=='object'].tolist()
cat_columns

['Location',
 'WindGustDir',
 'WindDir9am',
 'WindDir3pm',
 'RainToday',
 'RainTomorrow']

In [18]:
num_df = df[num_columns]
cat_df = df[cat_columns]
cat_df = pd.get_dummies(cat_df, drop_first=True)
cat_df.sample(5)

,Location_Albury,Location_AliceSprings,Location_BadgerysCreek,Location_Ballarat,Location_Bendigo,Location_Brisbane,Location_Cairns,Location_Canberra,Location_Cobar,Location_CoffsHarbour,...,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW,RainToday_Yes,RainTomorrow_Yes
14860,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
93331,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42382,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25943,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
117764,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
cat_df.sample(5)
y= cat_df["RainTomorrow_Yes"]
cat_df = cat_df.drop("RainTomorrow_Yes", axis='columns')
X = pd.concat([num_df, cat_df], axis=1)

In [20]:
X.sample(5)

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,...,WindDir3pm_NW,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW,RainToday_Yes
23649,20.1,26.3,0.0,5.600000,7.611178,39.0,28.0,20.0,73.0,73.0,...,0,0,0,0,0,0,0,0,0,0
135475,11.3,19.7,0.0,5.468232,7.611178,43.0,11.0,26.0,68.0,51.0,...,1,0,0,0,0,0,0,0,0,0
107275,24.0,38.2,0.0,23.800000,7.611178,52.0,24.0,33.0,12.0,5.0,...,0,0,0,0,0,0,0,0,0,0
2969,6.4,21.4,0.0,5.468232,7.611178,19.0,7.0,11.0,75.0,42.0,...,0,0,0,0,0,0,0,0,0,0
139126,18.7,33.5,0.0,7.400000,11.000000,41.0,15.0,22.0,71.0,32.0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
X.shape, y.shape

((123710, 108), (123710,))

In [22]:
sc=MinMaxScaler()
X_scaled = sc.fit_transform(X)
X_scaled[:5]

array([[0.51650943, 0.52362949, 0.00163221, 0.06343656, 0.52490879,
        0.2890625 , 0.21176471, 0.25882353, 0.71      , 0.22      ,
        0.44958678, 0.48      , 0.88888889, 0.50110334, 0.50843882,
        0.52207294, 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        ],
       [0.375     , 0.56521739, 0.        , 0.06343656, 0.52490879,
        0.2890625 , 0.02352941, 0.23529412, 0.44      , 0.25      ,
        0.49752066, 0.4912    , 0.49416236, 0.50110334, 0.51476793,
        0.57005758, 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        ],
       [0.50471698, 0.57655955, 0.        , 0.06343656, 0.52490879,
        0.3046875 , 0.2       , 0.28235294, 0.38      , 0.3       ,
        0.44793388, 0.5056    , 0.49416236, 0.22222222, 0.59493671,
        0.54894434, 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        ],
       [0.41745283, 0.62003781, 0.        , 0.06343656, 0.52490879,
        0.1328125 , 0.10588235, 0.08235294, 0.45      , 0.16      ,
        0.61322314, 0.5712    , 0.49416236, 0.50110334, 0.53375527,
        0.61228407, 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.61320755, 0.70132325, 0.00272035, 0.06343656, 0.52490879,
        0.265625  , 0.05882353, 0.21176471, 0.82      , 0.33      ,
        0.50082645, 0.4624    , 0.77777778, 0.88888889, 0.52742616,
        0.67370441, 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ]])

In [23]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(sampling_strategy='minority')
X_sm, y_sm = smote.fit_resample(X_scaled, y)
y_sm.value_counts()

0    96318
1    96318
Name: RainTomorrow_Yes, dtype: int64

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X_sm, y_sm, test_size=0.25, random_state=25, stratify=y_sm)

In [25]:
X_train.shape, y_train.shape

((144477, 108), (144477,))

In [26]:
X_test.shape, y_test.shape

((48159, 108), (48159,))

In [27]:
# Hyper Parameters Tuning
penalties = ['l1', 'l2']
C = [0.0001, 0.001, 0.01, 0.1, 1, 10, 100]
solvers = ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']
l1_ratios = [0.25, 0.5, 0.75]
lgr_best_score = 0
lgr_best_solver = str
lgr_best_c = 0
lgr_best_penalty = str
hyper_params = []
f1_Scores = []
kFolds = 5

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import f1_score, confusion_matrix

for s in solvers:
    for p in penalties:
        for c in C:
            if s == 'newton-cg' or 'lbfgs' or 'sag':
                if p =='l2':
                    lgr = LogisticRegression(penalty = p , C = c,  solver = s, max_iter = 100)
                    y_pred = cross_val_predict(lgr, X_train, y_train, cv = kFolds)
                    F1_score = f1_score(y_train, y_pred)
                    hyper_params.append([s,p,c]) 
                    f1_Scores.append(F1_score)
                    if F1_score>lgr_best_score:
                        lgr_best_score = F1_score
                        lgr_best_solver = s
                        lgr_best_c =c
                        lgr_best_penalty = p 
            if s == "liblinear":
                if p in ['l1', 'l2']:
                    lgr = LogisticRegression(penalty = p , C = c,  solver = s, max_iter = 100)
                    y_pred = cross_val_predict(lgr, X_train, y_train, cv = kFolds)
                    F1_score = f1_score(y_train, y_pred)
                    hyper_params.append([s,p,c]) 
                    f1_Scores.append(F1_score)
                    if F1_score>lgr_best_score:
                        lgr_best_score = F1_score
                        lgr_best_solver = s
                        lgr_best_c =c
                        lgr_best_penalty = p  
            if s == "saga":
                if p == "elasticnet":
                    for l1 in l1_ratios:
                        lgr = LogisticRegression(penalty = p , C = c,  solver = s, l1_ratio=l1, max_iter = 100)
                        lgr = LogisticRegression(penalty = p , C = c,  solver = s, max_iter = 100)
                        y_pred = cross_val_predict(lgr, X_train, y_train, cv = kFolds)
                        F1_score = f1_score(y_train, y_pred)
                        hyper_params.append([s,p,c]) 
                        f1_Scores.append(F1_score)
                        if F1_score>lgr_best_score:
                            lgr_best_score = F1_score
                            lgr_best_solver = s
                            lgr_best_c =c
                            lgr_best_penalty = p
                else:
                    lgr = LogisticRegression(penalty = p , C = c,  solver = s, max_iter = 100)
                    y_pred = cross_val_predict(lgr, X_train, y_train, cv = kFolds)
                    F1_score = f1_score(y_train, y_pred)
                    hyper_params.append([s,p,c]) 
                    f1_Scores.append(F1_score)
                    if F1_score>lgr_best_score:
                        lgr_best_score = F1_score
                        lgr_best_solver = s
                        lgr_best_c =c
                        lgr_best_penalty = p

/opt/anaconda3/envs/ml_env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/ml_env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/ml_env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/ml_env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/ml_env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/ml_env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/ml_env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/ml_env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/ml_env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/ml_env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/ml_env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/ml_env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/ml_env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/ml_env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/ml_env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/ml_env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

/opt/anaconda3/envs/ml_env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/ml_env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/ml_env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/ml_env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [29]:
hyper_params

[['newton-cg', 'l2', 0.0001],
 ['newton-cg', 'l2', 0.001],
 ['newton-cg', 'l2', 0.01],
 ['newton-cg', 'l2', 0.1],
 ['newton-cg', 'l2', 1],
 ['newton-cg', 'l2', 10],
 ['newton-cg', 'l2', 100],
 ['lbfgs', 'l2', 0.0001],
 ['lbfgs', 'l2', 0.001],
 ['lbfgs', 'l2', 0.01],
 ['lbfgs', 'l2', 0.1],
 ['lbfgs', 'l2', 1],
 ['lbfgs', 'l2', 10],
 ['lbfgs', 'l2', 100],
 ['liblinear', 'l1', 0.0001],
 ['liblinear', 'l1', 0.001],
 ['liblinear', 'l1', 0.01],
 ['liblinear', 'l1', 0.1],
 ['liblinear', 'l1', 1],
 ['liblinear', 'l1', 10],
 ['liblinear', 'l1', 100],
 ['liblinear', 'l2', 0.0001],
 ['liblinear', 'l2', 0.0001],
 ['liblinear', 'l2', 0.001],
 ['liblinear', 'l2', 0.001],
 ['liblinear', 'l2', 0.01],
 ['liblinear', 'l2', 0.01],
 ['liblinear', 'l2', 0.1],
 ['liblinear', 'l2', 0.1],
 ['liblinear', 'l2', 1],
 ['liblinear', 'l2', 1],
 ['liblinear', 'l2', 10],
 ['liblinear', 'l2', 10],
 ['liblinear', 'l2', 100],
 ['liblinear', 'l2', 100],
 ['sag', 'l2', 0.0001],
 ['sag', 'l2', 0.001],
 ['sag', 'l2', 0.01],
 ['sag', 'l2', 0.1],
 ['sag', 'l2', 1],
 ['sag', 'l2', 10],
 ['sag', 'l2', 100],
 ['saga', 'l1', 0.0001],
 ['saga', 'l1', 0.001],
 ['saga', 'l1', 0.01],
 ['saga', 'l1', 0.1],
 ['saga', 'l1', 1],
 ['saga', 'l1', 10],
 ['saga', 'l1', 100],
 ['saga', 'l2', 0.0001],
 ['saga', 'l2', 0.0001],
 ['saga', 'l2', 0.001],
 ['saga', 'l2', 0.001],
 ['saga', 'l2', 0.01],
 ['saga', 'l2', 0.01],
 ['saga', 'l2', 0.1],
 ['saga', 'l2', 0.1],
 ['saga', 'l2', 1],
 ['saga', 'l2', 1],
 ['saga', 'l2', 10],
 ['saga', 'l2', 10],
 ['saga', 'l2', 100],
 ['saga', 'l2', 100]]

In [30]:
index = f1_Scores.index(max(f1_Scores))
hyper_params[index]

['newton-cg', 'l2', 10]

In [31]:
lgr_best_penalty, lgr_best_c, lgr_best_solver

('l2', 10, 'newton-cg')

In [32]:
best_lgr = LogisticRegression(penalty = lgr_best_penalty, C = lgr_best_c, solver = lgr_best_solver, max_iter=5000)
best_lgr.fit(X_train, y_train)

LogisticRegression(C=10, max_iter=5000, solver='newton-cg')

In [33]:
y_train_predictions = best_lgr.predict(X_train)

In [35]:
score = f1_score(y_train, y_train_predictions)
score

0.8087418010836829

In [36]:
y_pred = best_lgr.predict(X_test)
y_pred[:5]

array([1, 0, 0, 1, 1], dtype=uint8)

In [37]:
from sklearn.metrics import classification_report, accuracy_score
print(classification_report(y_test, y_pred, target_names=['0','1']))
print(accuracy_score(y_train, y_train_predictions))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.82      0.81     24080
           1       0.81      0.80      0.81     24079

    accuracy                           0.81     48159
   macro avg       0.81      0.81      0.81     48159
weighted avg       0.81      0.81      0.81     48159

0.8096790492604359
0.8100043605556594